### ISSUE TITLE
Support non-standard metric names?

### ISSUE THREAD

**Issue by keirlawson** [vthriller/promql#1]
Appreciate this might well be out of the scope of what you want to do with this library, but it would be useful to me if there was an option to support metrics that contain periods (.) as various non-prometheus time series databases commonly use these in metric names.  Obviously this is not stictly valid promQL but if there was an option for it it could make this library useful for other TSDB querying.

**Comment by vthriller** [comment]
I quite like the idea actually. Let's hope Prometheus would never introduce any feature that would make periods syntactically significant…

**Comment by keirlawson** [comment]
I guess ideally it would be an option that consumers could choose to opt in to, but looking at the code its not immediately apparent how to achieve that.

**Comment by vthriller** [comment]
In nom, every parser combinator is a function under the hood, so it might be possible to substitute a number of macros with function declarations that accept extra arguments. In fact, [nom 5 actually encourages migration from macros to functions](https://github.com/Geal/nom/blob/5.1.0/doc/upgrading_to_nom_5.md#from-macros-to-functions).

**Comment by vthriller** [comment]
(For details, you can skim through *[Making a new parser from scratch](https://github.com/Geal/nom/blob/master/doc/making_a_new_parser_from_scratch.md)*)

**Comment by vthriller** [comment]
https://crates.io/crates/promql/0.4.0
